[package]
name = "minifn"
version = "0.1.0"
authors = ["Purple Hair Rust Bard <AshantiMutinta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
